#!/bin/bash
set -e

echo "[INFO] Adding Klayout APT Packages"
apt-get -y install --fix-missing \
    gcc \
    g++ \
    make \
    qtbase5-dev \
    qttools5-dev \
    libqt5xmlpatterns5-dev \
    qtmultimedia5-dev \
    libqt5multimediawidgets5 \
    libqt5svg5-dev \
    ruby \
    ruby-dev \
    python3 \
    python3-dev \
    libz-dev \
    libgit2-dev

strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
